blank_issues_enabled: false
contact_links:
  - name: Questions about Butterfly
    url: https://github.com/anzhiyu-c/hexo-theme-anzhiyu/discussions
    about: 一些使用问题请到 Discussion 询问。 Please ask questions in Discussion.

  - name: AnZhiYu Q&A
    url: https://anzhiy.cn/comments/
    about: AnZhiYu Q&A

  - name: QQ群
    url: https://jq.qq.com/?_wv=1027&k=v7NK7ELr
    about: "群号 464636182"
